### PR TITLE
Added Activity diagram to functional part of the report. Added description to technical part of the report

### PR DESCRIPTION
**Pull request by Sara-Eftekhar-Azam**

### CODE REVIEW

**Comment by Sara-Eftekhar-Azam** [comment]
> Please state what you updated in your activity diagram. Also please merge development to your branch since I merged all the design documents into 1.

I merged the development and this branch in now up to date. I think that my activity diagram is now complete (it is the same as I sent before in discord and I have only added it to the report). If you have any suggestion please let me know here or in discord so we can discuss it.

**Comment by Phaneron97** [comment]
> > > > Please state what you updated in your activity diagram. Also please merge development to your branch since I merged all the design documents into 1.
> > > 
> > > 
> > > I merged the development and this branch in now up to date. I think that my activity diagram is now complete (it is the same as I sent before in discord and I have only added it to the report). If you have any suggestion please let me know here or in discord so we can discuss it.
> > 
> > 
> > What does your activity diagram look like? What else did you change? This is unclear in your PR.
> 
> You are right. In my PR I only mentioned the activity diagram. I edited it to be more descriptive.
> 
> I have added my activity diagram to the report (the picture I sent before) Also, I added explanation and description to the technical part of the report (it was empty and I filled it with some explanations although it is not yet complete)

I don't see a picture of your diagram here.

**Comment by Sara-Eftekhar-Azam** [comment]
> > > > > Please state what you updated in your activity diagram. Also please merge development to your branch since I merged all the design documents into 1.
> > > > 
> > > > 
> > > > I merged the development and this branch in now up to date. I think that my activity diagram is now complete (it is the same as I sent before in discord and I have only added it to the report). If you have any suggestion please let me know here or in discord so we can discuss it.
> > > 
> > > 
> > > What does your activity diagram look like? What else did you change? This is unclear in your PR.
> > 
> > 
> > You are right. In my PR I only mentioned the activity diagram. I edited it to be more descriptive.
> > I have added my activity diagram to the report (the picture I sent before) Also, I added explanation and description to the technical part of the report (it was empty and I filled it with some explanations although it is not yet complete)
> 
> I don't see a picture of your diagram here.

I added it to the report. I will attach it here for simpler reference.
ActivityDiagram drawio

**Comment by Phaneron97** [comment]
> > > > > > Please state what you updated in your activity diagram. Also please merge development to your branch since I merged all the design documents into 1.
> > > > > 
> > > > > 
> > > > > I merged the development and this branch in now up to date. I think that my activity diagram is now complete (it is the same as I sent before in discord and I have only added it to the report). If you have any suggestion please let me know here or in discord so we can discuss it.
> > > > 
> > > > 
> > > > What does your activity diagram look like? What else did you change? This is unclear in your PR.
> > > 
> > > 
> > > You are right. In my PR I only mentioned the activity diagram. I edited it to be more descriptive.
> > > I have added my activity diagram to the report (the picture I sent before) Also, I added explanation and description to the technical part of the report (it was empty and I filled it with some explanations although it is not yet complete)
> > 
> > 
> > I don't see a picture of your diagram here.
> 
> I added it to the report. I will attach it here for simpler reference. ActivityDiagram drawio

We talked about this. This is not how the user should upload the images because it implies the user can skip uploading images altogether. Please account for this.

**Comment by Sara-Eftekhar-Azam** [comment]
OK. Just to make sure, the user has to upload both sides or only one side?

**Comment by Sara-Eftekhar-Azam** [comment]
I updated the image to make uploading images mandatory.

ActivityDiagram-v2 drawio

**Review by Bastiaan27 — APPROVED** [review]
Looks good to me

**Review by Phaneron97 — APPROVED** [review]
With the stuff added by @NinoHector1337: looks good to me

**Comment by NinoHector1337** [comment]
I've reworked the Activity Diagram + the text about it. 

ActivityDiagram-v2 drawio-1

Picture here.

**Pull request merged**
