### PR TITLE
Grapical design V2

### PR DESCRIPTION
**Pull request by Bastiaan27**
The new graphical design is described in detail in the paper now.

app_flow
image
image
image
image
image
image
image

### CODE REVIEW

**Review by Phaneron97 — APPROVED** [review]
I understand your choice of using fullwidth instead of sidenote since the text is too long to fit otherwise. Nice additions! Can be merged. Also: 3am, bro do you ever sleep? lol

**Review by Sara-Eftekhar-Azam — APPROVED** [review]
I think it is good. The graphical explanation now has proper content. Maybe the example image for a tile is better to be an image with while background to be more formal instead of on grass.

**Review by Sara-Eftekhar-Azam — COMMENTED** [review]
After the model makes a prediction, we show the user an example picture of the tile was have predicted. I think it is better to use an image as example that has white background (or any other one color backgroun) since it will be more formal. I understand that we might not have some picture write now, in that case, we can get such image from client or use an image with a good background from avaialbe images.

**Comment by Bastiaan27** [comment]
Some adjustments have been made in the design and text of the pages, see the last 2 commits for the exact changes in text. 
Here are the adjusted pages of the app:
prediction_made_app
prediction_analysing_app
submit_front_app
app_flow

**Review by Phaneron97 — CHANGES_REQUESTED** [review]
Please exclude any compile files from latex, they should already be included in the `.gitignore`. you only need to remove them from your commit with `git -r --cached <latex compile files>` I think.

**Pull request merged**
