### PR TITLE
Create vgg_train.py

### PR DESCRIPTION
**Pull request by Sara-Eftekhar-Azam**
I added VGG19 model with the help of ChatGPT. I attached the description file of what I did to this message.

[vgg19.docx](https://github.com/Phaneron97/BDA_proj_rooftiles/files/14652857/vgg19.docx)

### CODE REVIEW

**Comment by Sara-Eftekhar-Azam** [comment]
Here is the PDF version 
[vgg19.pdf](https://github.com/Phaneron97/BDA_proj_rooftiles/files/14652872/vgg19.pdf)

**Review by Phaneron97 — CHANGES_REQUESTED** [review]
Please don't push this to data_analysis. Instead make a new folder in code/ called `modelconcepts` (maybe?) and within `modelconcepts` a new folder with your specific code.

**Comment by Sara-Eftekhar-Azam** [comment]
I changed the location.

**Review by Phaneron97 — CHANGES_REQUESTED** [review]
As I said, please place your code in a folder with a name of your own choosing within `modelconcepts`, not directly into `modelconcepts` itself since we will probably update this folder with more models in the future.

**Review by Sara-Eftekhar-Azam — COMMENTED** [review]
I changed the location

**Review by Phaneron97 — APPROVED** [review]
Good, can be merged.

**Pull request merged**
